### ISSUE TITLE
Incorrect error message on incompatible service

### ISSUE THREAD

**Issue by Fayti1703** [prodzpod/ZeroDayToolKit#1]
Running an cracker executable against a port is *open*, but not compatible with the executable produces the message
> Target Port is Closed
> Execution failed

in the terminal. This does not match the base game behavior; the message *should* be

> Target Port running incompatible service for this executable
> Exeuction failed

To reproduce:
1. Load an Extension with `PacketHeaderInjection`, `SSHCrack` and a default security-0 node.
2. Connect to the node.
3. Run `PacketHeaderInjection 22`.
3.a Try running `SSHCrack 80` to compare.

[The relevant check is here](https://github.com/prodzpod/ZeroDayToolKit/blob/ce5593d864ee68b73c23ff9d7661e414139994bc/Executibles/ZeroDayEXE.cs#L54-L59). Most likely this will need to be split into multiple conditions.

**Comment by prodzpod** [comment]
's good now
